# Generated by Django 4.0 on 2022-01-22 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('strength', models.IntegerField(default=5)),
                ('perception', models.IntegerField(default=5)),
                ('agility', models.IntegerField(default=5)),
                ('intelligence', models.IntegerField(default=5)),
                ('endurance', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='Character')),
                ('nbVictory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Universe')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='app.character')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='app.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universe'),
        ),
        migrations.CreateModel(
            name='BattleRoyale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nbFighter', models.IntegerField(blank=True, default=0)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.character')),
            ],
        ),
    ]
