# Generated by Django 4.0 on 2022-01-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_character_endurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterUniverseJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.character')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universe')),
            ],
        ),
    ]
