# Generated by Django 4.0 on 2022-01-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_characteruniversejoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='app.character'),
        ),
    ]
