# Generated by Django 4.0 on 2022-01-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_fight_fighter1_alter_fight_fighter2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattleRoyale',
            new_name='BattleUniverse',
        ),
    ]
