# Generated by Django 4.0 on 2022-01-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_universe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterUniverseJoin',
            new_name='CharacterUniverse',
        ),
        migrations.RemoveField(
            model_name='battleuniverse',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='character',
            name='universe',
        ),
        migrations.CreateModel(
            name='BattleUniverseCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.battleuniverse')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.character')),
            ],
        ),
    ]
