# Generated by Django 4.0 on 2022-01-27 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_characteruniversejoin_characteruniverse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleuniverse',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='battleuniverse',
            name='nbFighter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
