# Generated by Django 4.0 on 2022-01-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_fighter_battleuniversecharacter_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='battleUniverse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.battleuniverse'),
        ),
    ]
