# Generated by Django 4.0 on 2022-01-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_battleuniverse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('-name',)},
        ),
    ]
