# Generated by Django 4.0 on 2022-01-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_character_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
    ]
