# Generated by Django 4.0 on 2022-01-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
