# Generated by Django 4.0 on 2022-01-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
